# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Codersjunto
email: barrettpaulj@gmail.com
description: "My posts concerning security, programming, administration, ..."
baseurl: ""
url: "http://paul-j-barrett.github.io"
twitter_username: codersjunto
github_username:  paul-j-barrett
facebook_username: codersjunto
googlep_username: 
website:	"http://www.codersjunto.com"

# Build settings
markdown: kramdown
